### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/pauromeubruguera-instagramPost#1]
# Revisión - Aprobado
- [x] Estilo de código y limpieza
# Feedback
- ¡Buen trabajo @pauromeubruguera  . Muchas felicidades !
## Estilo de código y limpieza
- ¡Muy bien hecho!
## Mejores prácticas/comentarios
- Aunque no se pedía en el ejercicio, muy bien implementada la interactividad de los iconos :v:

**Comment by pauromeubruguera** [comment]
Gracias! :)

**Comment by EduardoHernandezGuzman** [comment]
Muy buen trabajo. A por el siguiente!!!
